# =============================================================================
# Simplified Telegram Bot - Cloudflare Workers Configuration
# =============================================================================
# Simplified configuration for the basic 2-command bot
# =============================================================================

name = "help-with-job-search-telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "c8f793821e2b05647f669d4f13b51f0e"
keep_old_versions = 3

# =============================================================================
# Development Environment
# =============================================================================

[env.development]
name = "help-with-job-search-telegram-bot-dev"
workers_dev = true

# KV Namespace for simple session storage
[[env.development.kv_namespaces]]
binding = "SESSIONS"
id = "a93feb9ab1404806ad4649d05de50947"

# D1 Database for basic logging
[[env.development.d1_databases]]
binding = "LOGS_DB"
database_name = "telegram-bot-logs"
database_id = "f393809f-9a96-4fab-9e61-695b3331f962"

# AI binding for PDF text extraction
[env.development.ai]
binding = "AI"

# =============================================================================
# Staging Environment
# =============================================================================

[env.staging]
name = "help-with-job-search-telegram-bot-staging"
workers_dev = true

# KV Namespace for simple session storage
[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "a45656fd830b4668a05943bbb5afe793"

# D1 Database for basic logging
[[env.staging.d1_databases]]
binding = "LOGS_DB"
database_name = "telegram-bot-logs-staging"
database_id = "163e1614-01a5-46a9-b718-674fc8a34f85"

# AI binding for PDF text extraction
[env.staging.ai]
binding = "AI"

# Environment identifier
[env.staging.vars]
ENVIRONMENT = "staging"

# Basic staging configuration
BOT_USERNAME_STAGING = "job_search_help_staging_bot"
WORKER_NAME_STAGING = "help-with-job-search-telegram-bot-staging"
WORKER_URL_STAGING = "https://help-with-job-search-telegram-bot-staging.vova-likes-smoothy.workers.dev"

# =============================================================================
# Production Environment
# =============================================================================

[env.production]
name = "help-with-job-search-telegram-bot"
workers_dev = true

# KV Namespace for simple session storage
[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "06ccf718d2f4494aad2398b23c644b11"

# D1 Database for basic logging
[[env.production.d1_databases]]
binding = "LOGS_DB"
database_name = "telegram-bot-logs-production"
database_id = "50f03a22-7301-401f-bde5-2c34b07975bc"

# AI binding for PDF text extraction
[env.production.ai]
binding = "AI"

# Environment identifier
[env.production.vars]
ENVIRONMENT = "production"

# Basic production configuration
BOT_USERNAME_PRODUCTION = "job_search_help_bot"
WORKER_NAME_PRODUCTION = "help-with-job-search-telegram-bot"
WORKER_URL_PRODUCTION = "https://help-with-job-search-telegram-bot.vova-likes-smoothy.workers.dev"


# =============================================================================
# Local Development Configuration
# =============================================================================

[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"

# =============================================================================
# Deployment Configuration
# =============================================================================

# =============================================================================
# Comments and Documentation
# =============================================================================

# Simplified bot configuration for basic resume/job ad collection.
# Required secrets to set via wrangler:
# - TELEGRAM_BOT_TOKEN (your bot token from @BotFather)
