name: Deploy to Production

# Only deploy to production when pull requests are merged to main
# This ensures code has been reviewed and tested in staging first
on:
  push:
    branches: [main]
  # Allow manual deployment for emergency releases
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: true
        default: 'Emergency release'

permissions:
  contents: read
  issues: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to Production Environment
    # Only run if this is a push to main (indicating a merged PR)
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Get full history for better deployment tracking
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Build application
        run: npm run build:ci

      - name: Run tests
        run: npm test

      - name: Production deployment pre-flight checks
        run: |
          echo "🚀 Starting production deployment pre-flight checks..."
          echo "📦 Repository: ${{ github.repository }}"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "🔢 Commit: ${{ github.sha }}"
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "⚠️ Manual deployment triggered"
            echo "📝 Reason: ${{ github.event.inputs.reason }}"
          else
            echo "✅ Automatic deployment from merged PR"
          fi

      - name: Check production deployment prerequisites  
        run: |
          echo "🔍 Checking production deployment prerequisites..."
          
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "❌ CLOUDFLARE_API_TOKEN secret is not set"
            echo "📋 Please set this secret in GitHub repository settings"
            echo "🔗 Guide: https://github.com/${{ github.repository }}/blob/main/.github/SECRETS_SETUP.md"
            exit 1
          else
            echo "✅ CLOUDFLARE_API_TOKEN is set"
          fi
          
          if [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
            echo "❌ CLOUDFLARE_ACCOUNT_ID secret is not set"
            echo "📋 Please set this secret in GitHub repository settings"
            exit 1
          else
            echo "✅ CLOUDFLARE_ACCOUNT_ID is set"
          fi
          
          if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN_PRODUCTION }}" ]; then
            echo "❌ TELEGRAM_BOT_TOKEN_PRODUCTION secret is not set"
            echo "📋 Please set the production bot token in GitHub repository settings"
            echo "⚠️ Use a different bot token than staging for security"
            exit 1
          else
            echo "✅ TELEGRAM_BOT_TOKEN_PRODUCTION is set"
          fi
          
          if [ -z "${{ secrets.OPENAI_API_KEY_PRODUCTION }}" ]; then
            echo "⚠️ OPENAI_API_KEY_PRODUCTION secret is not set"
            echo "📋 AI features will not work in production"
          else
            echo "✅ OPENAI_API_KEY_PRODUCTION is set"
          fi
          
          if [ -z "${{ secrets.WEBHOOK_SECRET_PRODUCTION }}" ]; then
            echo "⚠️ WEBHOOK_SECRET_PRODUCTION not set, using default"
            echo "📋 Consider setting a unique webhook secret for production security"
          else
            echo "✅ WEBHOOK_SECRET_PRODUCTION is set"
          fi

      - name: Deploy to Cloudflare Workers (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_PRODUCTION }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_PRODUCTION }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET_PRODUCTION || 'production-webhook-secret-default' }}
          ADMIN_PASSWORD_PRODUCTION: ${{ secrets.ADMIN_PASSWORD_PRODUCTION || 'admin123' }}

      - name: Set production webhook
        if: success()
        run: |
          echo "🔗 Setting up production webhook..."
          
          # Extract bot token for webhook setup
          BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN_PRODUCTION }}"
          WEBHOOK_SECRET="${{ secrets.WEBHOOK_SECRET_PRODUCTION || 'production-webhook-secret-default' }}"
          
          # Get the production worker URL from wrangler.toml
          WORKER_URL="https://help-with-job-search-telegram-bot.$(echo '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}' | head -c 8).workers.dev"
          
          echo "🌐 Setting webhook URL: ${WORKER_URL}/webhook"
          
          RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/setWebhook" \
            -H "Content-Type: application/json" \
            -d "{\"url\": \"${WORKER_URL}/webhook\", \"secret_token\": \"${WEBHOOK_SECRET}\"}")
          
          echo "📞 Webhook response: $RESPONSE"
          
          # Check if webhook was set successfully
          if echo "$RESPONSE" | grep -q '"ok":true'; then
            echo "✅ Production webhook set successfully"
          else
            echo "❌ Failed to set production webhook"
            echo "🔍 Response: $RESPONSE"
            exit 1
          fi

      - name: Health check production deployment
        if: success()
        run: |
          echo "🏥 Running production health check..."
          
          # Get the production worker URL
          WORKER_URL="https://help-with-job-search-telegram-bot.$(echo '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}' | head -c 8).workers.dev"
          
          echo "🔍 Checking: ${WORKER_URL}/health"
          
          # Wait a moment for deployment to stabilize
          sleep 10
          
          # Perform health check
          HEALTH_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "${WORKER_URL}/health" || echo "000")
          
          if [ "$HEALTH_RESPONSE" = "200" ]; then
            echo "✅ Production health check passed (HTTP $HEALTH_RESPONSE)"
          else
            echo "⚠️ Production health check returned HTTP $HEALTH_RESPONSE"
            echo "🔍 This might be normal if the /health endpoint is not implemented"
          fi

      - name: Create deployment issue for tracking
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentTime = new Date().toISOString();
            const commitSha = context.sha.substring(0, 8);
            const deploymentReason = context.eventName === 'workflow_dispatch' 
              ? `Manual deployment: ${{ github.event.inputs.reason }}`
              : 'Automatic deployment from merged PR';
            
            const issueBody = `## 🚀 Production Deployment Completed
            
            **📅 Deployment Time**: ${deploymentTime}
            **🔢 Commit**: ${commitSha}
            **🌿 Branch**: ${{ github.ref_name }}
            **📝 Reason**: ${deploymentReason}
            
            ### 🤖 Production Bot Information
            - **Environment**: Production
            - **Worker Name**: help-with-job-search-telegram-bot
            - **Deployment**: Cloudflare Workers
            
            ### ✅ Deployment Checklist
            - [x] TypeScript compilation successful
            - [x] Tests passed
            - [x] Cloudflare Workers deployment successful
            - [x] Production webhook configured
            - [x] Health check completed
            
            ### 🔍 Monitoring
            Please monitor the production bot for the next 30 minutes to ensure:
            1. Bot responds to /start command
            2. Resume analysis features work correctly
            3. No error spikes in Cloudflare Analytics
            4. Performance remains stable
            
            ### 🚨 Rollback Procedure
            If issues are detected, rollback using:
            \`\`\`bash
            wrangler rollback --env production
            \`\`\`
            
            ---
            **🤖 Automated deployment tracking issue**
            Deployment ID: ${context.runId}`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚀 Production Deployment - ${commitSha} - ${deploymentTime}`,
              body: issueBody,
              labels: ['deployment', 'production']
            });

      - name: Deployment summary
        if: always()
        run: |
          echo "📊 Production Deployment Summary"
          echo "================================"
          echo "📦 Repository: ${{ github.repository }}"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "🔢 Commit: ${{ github.sha }}"
          echo "🕐 Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "🚀 Status: ${{ job.status }}"
          
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Production deployment completed successfully!"
            echo "🤖 The production Telegram bot is now running the latest version"
            echo "📱 Users can interact with the updated bot immediately"
          else
            echo "❌ Production deployment failed"
            echo "🔍 Check the logs above for error details"
            echo "📞 Consider rolling back if necessary"
          fi
